const actionType = {
    GET_HOME: 'GET_HOME',
    SET_CURRENT_SONG_ID: 'SET_SONG_ID',
    SET_CURRENT_SONG_DATA: 'SET_SONG_DATA',
    SET_CURRENT_ALBUM_ID: 'SET_ALBUM_DATA',
    PLAY_SONG: 'PLAY_SONG',
    SET_ALBUM: 'SET_ALBUM',
    GET_ALBUM: 'GET_ALBUM',

    LOADING: 'LOADING'
}

export default actionType